=== AdsonRoberto/InterfacesCustomizadasJB/JBEmptyProject/app/src/main/assets/config/schema/jb-codegen-mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="jb-codegen-mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entity" type="entity-type" 
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="enumeration" type="enumeration-type" 
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="entity-type">
		<xs:sequence>
			<xs:element name="jb-entity" type="jb-entity-type" />
			
			<xs:element name="attribute" type="attribute-type"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="method" type="method-type" 
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="class" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="enumeration-type">
		<xs:sequence>
			<xs:element name="jb-enumeration" type="jb-enumeration-type" />
		</xs:sequence>
		<xs:attribute name="enum" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="attribute-type">
		<xs:sequence>
			<xs:element name="jb-attribute" type="jb-attribute-type"
				minOccurs="0" />
				
			<xs:element name="jb-temporal" type="jb-temporal-type"
				minOccurs="0" />
			<xs:element name="jb-large" type="jb-large-type"
				minOccurs="0" />
		</xs:sequence>
		
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="enclosing-type" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="method-type">
		<xs:sequence>
			<xs:element name="jb-action" type="jb-action-type"
				minOccurs="0" />
			<xs:element name="jb-description" type="jb-description-type"
				minOccurs="0" />
					
			<xs:element name="parameter" type="parameter-type" 
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="enclosing-type" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="parameter-type">
		<xs:sequence>
			<xs:element name="jb-parameter" type="jb-parameter-type"
				minOccurs="0" />
		</xs:sequence>
		
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="enclosing-type" type="xs:string" use="required" />
	</xs:complexType>
	
	<!-- DOMAIN -->

	<xs:complexType name="jb-entity-type">
		<xs:attribute name="label" type="xs:string" use="required" />
		<xs:attribute name="collectionLabel" type="xs:string" use="required" />
		<xs:attribute name="icon" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="jb-enumeration-type"/>

	<xs:complexType name="jb-attribute-type">
		<xs:sequence>
			<xs:element name="order" type="xs:integer" />
			<xs:element name="name" type="xs:string" />
			<xs:element name="id" type="xs:boolean" />
			<xs:element name="views">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="kind-view" type="kind-view-type"
							minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="jb-action-type">
		<xs:sequence>
			<xs:element name="order" type="xs:integer" />
			<xs:element name="name" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="jb-parameter-type">
		<xs:sequence>
			<xs:element name="order" type="xs:integer" />
			<xs:element name="name" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="kind-view-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ALL" />
			<xs:enumeration value="INSERT" />
			<xs:enumeration value="DETAIL" />
			<xs:enumeration value="EDIT" />
			<xs:enumeration value="FIND" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- VISUAL -->
	
	<xs:complexType name="jb-large-type"/>
	
	<xs:complexType name="jb-description-type">
		<xs:sequence>
			<xs:element name="value" type="description-type" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="jb-temporal-type">
		<xs:sequence>
			<xs:element name="value" type="temporal-type" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="description-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PRIMARY" />
			<xs:enumeration value="SECONDARY" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="temporal-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DATE" />
			<xs:enumeration value="TIME" />
			<xs:enumeration value="TIMESTAMP" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== AdsonRoberto/InterfacesCustomizadasJB/JBEmptyProject/app/src/main/assets/config/mapping/codegen/jb-codegen-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<jb-codegen-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schema/jb-codegen-mapping.xsd">
	<entity class="org.jb.model.Catalogo">
		<jb-entity collectionLabel="Catalogos" icon="" label="Catalogo" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-attribute>
				<order>0</order>
				<name>Identificador</name>
				<id>true</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="nome" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-attribute>
				<order>1</order>
				<name>Nome</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="descricao" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-attribute>
				<order>2</order>
				<name>Descrição</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="produtos" type="java.util.List"
			enclosing-type="org.jb.model.Produto">
			<jb-attribute>
				<order>3</order>
				<name>Produtos</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<method name="getNome" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-description>
				<value>PRIMARY</value>
			</jb-description>
		</method>
		<method name="getDescricao" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-description>
				<value>SECONDARY</value>
			</jb-description>
		</method>
		<method enclosing-type="void" name="adicionarProduto" type="void">
			<jb-action>
				<order>1</order>
				<name>Adicionar Produto</name>
			</jb-action>
			<parameter enclosing-type="org.jb.model.Produto" name="produto"
				type="org.jb.model.Produto">
				<jb-parameter>
					<order>1</order>
					<name>Produto</name>
				</jb-parameter>
			</parameter>
		</method>
	</entity>
	<entity class="org.jb.model.Cliente">
		<jb-entity collectionLabel="Clientes" icon="" label="Cliente" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-attribute>
				<order>0</order>
				<name>Identificador</name>
				<id>true</id>
				<views>
					<kind-view>DETAIL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="nome" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-attribute>
				<order>1</order>
				<name>Nome</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="sexo" type="org.jb.model.Sexo"
			enclosing-type="org.jb.model.Sexo">
			<jb-attribute>
				<order>2</order>
				<name>Sexo</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="dataNascimento" type="java.util.Date"
			enclosing-type="java.util.Date">
			<jb-attribute>
				<order>3</order>
				<name>Data de Nascimento</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
			<jb-temporal>
				<value>DATE</value>
			</jb-temporal>
		</attribute>
		<attribute name="pedidos" type="java.util.List"
			enclosing-type="org.jb.model.Pedido">
			<jb-attribute>
				<order>4</order>
				<name>Pedidos</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<method name="getId" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-description>
				<value>PRIMARY</value>
			</jb-description>
		</method>
		<method name="getNome" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-description>
				<value>SECONDARY</value>
			</jb-description>
		</method>
	</entity>
	<entity class="org.jb.model.Item">
		<jb-entity collectionLabel="Itens" icon="" label="Item" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-attribute>
				<order>0</order>
				<name>Identificador</name>
				<id>true</id>
				<views>
					<kind-view>DETAIL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="pedido" type="org.jb.model.Pedido"
			enclosing-type="org.jb.model.Pedido">
			<jb-attribute>
				<order>1</order>
				<name>Pedido</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="produto" type="org.jb.model.Produto"
			enclosing-type="org.jb.model.Produto">
			<jb-attribute>
				<order>2</order>
				<name>Produto</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="quantidade" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-attribute>
				<order>3</order>
				<name>Quantidade</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="valor" type="java.lang.Double"
			enclosing-type="java.lang.Double">
			<jb-attribute>
				<order>4</order>
				<name>Valor</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<method name="getProduto" type="org.jb.model.Produto"
			enclosing-type="org.jb.model.Produto">
			<jb-description>
				<value>PRIMARY</value>
			</jb-description>
		</method>
		<method name="getQuantidade" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-description>
				<value>SECONDARY</value>
			</jb-description>
		</method>
	</entity>
	<entity class="org.jb.model.Pedido">
		<jb-entity collectionLabel="Pedidos" icon="" label="Pedido" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-attribute>
				<order>0</order>
				<name>Identificador</name>
				<id>true</id>
				<views>
					<kind-view>DETAIL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="cliente" type="org.jb.model.Cliente"
			enclosing-type="org.jb.model.Cliente">
			<jb-attribute>
				<order>1</order>
				<name>Cliente</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="data" type="java.util.Date" enclosing-type="java.util.Date">
			<jb-attribute>
				<order>2</order>
				<name>Data</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
			<jb-temporal>
				<value>DATE</value>
			</jb-temporal>
		</attribute>
		<attribute name="situacao" type="org.jb.model.SituacaoPedido"
			enclosing-type="org.jb.model.SituacaoPedido">
			<jb-attribute>
				<order>3</order>
				<name>Situação</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="itens" type="java.util.List"
			enclosing-type="org.jb.model.Item">
			<jb-attribute>
				<order>4</order>
				<name>Itens</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<method name="getCliente" type="org.jb.model.Cliente"
			enclosing-type="org.jb.model.Cliente">
			<jb-description>
				<value>PRIMARY</value>
			</jb-description>
		</method>
		<method name="getData" type="java.util.Date" enclosing-type="java.util.Date">
			<jb-description>
				<value>SECONDARY</value>
			</jb-description>
		</method>
	</entity>
	<entity class="org.jb.model.Produto">
		<jb-entity collectionLabel="Produtos" icon="" label="Produto" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<jb-attribute>
				<order>0</order>
				<name>Identificador</name>
				<id>true</id>
				<views>
					<kind-view>DETAIL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="descricao" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-attribute>
				<order>1</order>
				<name>Descrição</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="valor" type="java.lang.Double"
			enclosing-type="java.lang.Double">
			<jb-attribute>
				<order>2</order>
				<name>Valor</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<attribute name="catalogos" type="java.util.List"
			enclosing-type="org.jb.model.Catalogo">
			<jb-attribute>
				<order>3</order>
				<name>Catalogos</name>
				<id>false</id>
				<views>
					<kind-view>ALL</kind-view>
				</views>
			</jb-attribute>
		</attribute>
		<method name="getDescricao" type="java.lang.String"
			enclosing-type="java.lang.String">
			<jb-description>
				<value>PRIMARY</value>
			</jb-description>
		</method>
		<method name="getValor" type="java.lang.Double"
			enclosing-type="java.lang.Double">
			<jb-description>
				<value>SECONDARY</value>
			</jb-description>
		</method>
	</entity>
	<enumeration enum="org.jb.model.Perfil">
		<jb-enumeration />
	</enumeration>
	<enumeration enum="org.jb.model.SituacaoPedido">
		<jb-enumeration />
	</enumeration>
	<enumeration enum="org.jb.model.Sexo">
		<jb-enumeration />
	</enumeration>
</jb-codegen-mapping>
