=== AdsonRoberto/InterfacesCustomizadasJB/JBEmptyProject/app/src/main/assets/config/schema/jb-persistence-mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="jb-persistence-mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entity" type="entity-type" 
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="entity-type">
		<xs:sequence>
			<xs:element name="web-entity" type="web-entity-type" />
			<xs:element name="attribute" type="attribute-type"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="method" type="method-type" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="class" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="attribute-type">
		<xs:sequence>
			<xs:element name="web-aggregation" type="web-aggregation-type"
				minOccurs="0" />
			<xs:element name="web-composition" type="web-composition-type"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="enclosing-type" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="method-type">
		<xs:sequence>
			<xs:element name="web-action" type="web-action-type"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="enclosing-type" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="web-entity-type">
		<xs:sequence>
			<xs:element name="insert" type="request-type" />
			<xs:element name="update" type="request-type" />
			<xs:element name="delete" type="request-type" />
			<xs:element name="find" type="request-type" />
			<xs:element name="findById" type="request-type" />
			<xs:element name="findAll" type="request-type" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="web-aggregation-type">
		<xs:sequence>
			<xs:element name="insert" type="request-type" />
			<xs:element name="delete" type="request-type" />
			<xs:element name="list" type="request-type" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="web-composition-type">
		<xs:sequence>
			<xs:element name="list" type="request-type" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="web-action-type">
		<xs:sequence>
			<xs:element name="request" type="request-type" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="request-type">
		<xs:sequence>
			<xs:element name="path" type="xs:string" />
			<xs:element name="method" type="http-method-type"
				minOccurs="0" />
			<xs:element name="consumedType" type="text-type"
				minOccurs="0" />
			<xs:element name="producedType" type="text-type"
				minOccurs="0" />
			<xs:element name="pathParameters" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="pathParam" type="parameter-type"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="queryParameters" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="queryParam" type="parameter-type"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="http-method-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GET" />
			<xs:enumeration value="POST" />
			<xs:enumeration value="PUT" />
			<xs:enumeration value="DELETE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="text-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="text/plain" />
			<xs:enumeration value="text/xml" />
			<xs:enumeration value="text/json" />
			<xs:enumeration value="application/xml" />
			<xs:enumeration value="application/json" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="parameter-type">
		<xs:sequence>
			<xs:element name="param" type="xs:string" />
			<xs:element name="jb-text-value" type="xs:string"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AdsonRoberto/InterfacesCustomizadasJB/JBEmptyProject/app/src/main/assets/config/mapping/persistence/jb-persistence-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<jb-persistence-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schema/jb-persistence-mapping.xsd">
	<entity class="org.jb.model.Produto">
		<web-entity>
			<insert>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/insert</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</insert>
			<update>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/update</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</update>
			<delete>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/delete/{id}</path>
				<method>DELETE</method>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</delete>
			<find>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/find</path>
				<method>POST</method>
				<producedType>text/xml</producedType>
				<queryParameters>
					<queryParam>
						<param>descricao</param>
					</queryParam>
					<queryParam>
						<param>valor</param>
					</queryParam>
				</queryParameters>
			</find>
			<findById>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/findById/{id}</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</findById>
			<findAll>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/all</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
			</findAll>
		</web-entity>

		<attribute name="catalogos" type="java.util.List"
			enclosing-type="org.jb.model.Catalogo">
			<web-aggregation>
				<insert>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/addCatalogo</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>produto</param>
						</queryParam>
						<queryParam>
							<param>catalogo</param>
						</queryParam>
					</queryParameters>
				</insert>
				<delete>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/removeCatalogo</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>produto</param>
						</queryParam>
						<queryParam>
							<param>catalogo</param>
						</queryParam>
					</queryParameters>
				</delete>
				<list>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/produtos/listaCatalogos</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>produto</param>
						</queryParam>
					</queryParameters>
				</list>
			</web-aggregation>
		</attribute>
	</entity>
	<entity class="org.jb.model.Catalogo">
		<web-entity>
			<insert>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/insert</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</insert>
			<update>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/update</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</update>
			<delete>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/delete/{id}</path>
				<method>DELETE</method>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</delete>
			<find>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/find</path>
				<method>POST</method>
				<producedType>text/xml</producedType>
				<queryParameters>
					<queryParam>
						<param>descricao</param>
					</queryParam>
					<queryParam>
						<param>valor</param>
					</queryParam>
				</queryParameters>
			</find>
			<findById>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/findById/{id}</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</findById>
			<findAll>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/all</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
			</findAll>
		</web-entity>

		<attribute name="produtos" type="java.util.List"
			enclosing-type="org.jb.model.Produto">
			<web-aggregation>
				<insert>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/addProduto</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>catalogo</param>
						</queryParam>
						<queryParam>
							<param>produto</param>
						</queryParam>
					</queryParameters>
				</insert>
				<delete>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/removeProduto</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>catalogo</param>
						</queryParam>
						<queryParam>
							<param>produto</param>
						</queryParam>
					</queryParameters>
				</delete>
				<list>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/listaProdutos</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>catalogo</param>
						</queryParam>
					</queryParameters>
				</list>
			</web-aggregation>
		</attribute>

		<method name="adicionarProduto" type="void" enclosing-type="void">
			<web-action>
				<request>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/catalogos/addProduto</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>catalogo</param>
						</queryParam>
						<queryParam>
							<param>produto</param>
						</queryParam>
					</queryParameters>
				</request>
			</web-action>
		</method>
	</entity>
	<entity class="org.jb.model.Pedido">
		<web-entity>
			<insert>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/pedidos/insert</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</insert>
			<update>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/pedidos/update</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</update>
			<delete>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/pedidos/delete/{id}</path>
				<method>DELETE</method>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</delete>
			<find>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/pedidos/find</path>
				<method>POST</method>
				<producedType>text/xml</producedType>
				<queryParameters>
					<queryParam>
						<param>nome</param>
					</queryParam>
					<queryParam>
						<param>sexo</param>
					</queryParam>
					<queryParam>
						<param>dataDeNascimento</param>
					</queryParam>
				</queryParameters>
			</find>
			<findById>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/pedidos/findById/{id}</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</findById>
			<findAll>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/pedidos/all</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
			</findAll>
		</web-entity>

		<attribute name="itens" type="java.util.List"
			enclosing-type="org.jb.model.Item">
			<web-composition>
				<list>
					<path>http://192.168.25.7:8080/JBWebCrudApp/services/itens/find</path>
					<method>POST</method>
					<producedType>text/xml</producedType>
					<queryParameters>
						<queryParam>
							<param>pedido</param>
						</queryParam>
					</queryParameters>
				</list>
			</web-composition>
		</attribute>
	</entity>
	<entity class="org.jb.model.Item">
		<web-entity>
			<insert>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/itens/insert</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</insert>
			<update>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/itens/update</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</update>
			<delete>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/itens/delete/{id}</path>
				<method>DELETE</method>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</delete>
			<find>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/itens/find</path>
				<method>POST</method>
				<producedType>text/xml</producedType>
				<queryParameters>
					<queryParam>
						<param>pedido</param>
					</queryParam>
					<queryParam>
						<param>produto</param>
					</queryParam>
					<queryParam>
						<param>quantidade</param>
					</queryParam>
					<queryParam>
						<param>valor</param>
					</queryParam>
				</queryParameters>
			</find>
			<findById>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/itens/findById/{id}</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
				<pathParameters>
					<pathParam>
						<param>{id}</param>
					</pathParam>
				</pathParameters>
			</findById>
			<findAll>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/itens/all</path>
				<method>GET</method>
				<producedType>text/xml</producedType>
			</findAll>
		</web-entity>

	</entity>
	<entity class="org.jb.model.Cliente">
		<web-entity>
			<insert>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/clientes/insert</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</insert>
			<update>
				<path>http://192.168.25.7:8080/JBWebCrudApp/services/clientes/update</path>
				<method>PUT</method>
				<consumedType>text/xml</consumedType>
			</update>
			<delete>
