=== AdsonRoberto/InterfacesCustomizadasJB/JBEmptyProject/app/src/main/assets/config/schema/jb-stream-mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="jb-stream-mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entity" type="entity-type" 
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="entity-type">
		<xs:sequence>
			<xs:element name="stream-entity" type="stream-entity-type" />
			<xs:element name="attribute" type="attribute-type"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="class" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="attribute-type">
		<xs:sequence>
			<xs:element name="stream-attribute" type="stream-attribute-type"
				minOccurs="0" />
			<xs:element name="stream-element" type="stream-element-type"
				minOccurs="0" />
			<xs:element name="stream-enumerated" type="stream-enumerated-type"
				minOccurs="0" />
			<xs:element name="stream-temporal" type="stream-temporal-type"
				minOccurs="0" />
			<xs:element name="stream-transient" type="stream-transient-type"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="enclosing-type" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="stream-entity-type">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="collectionName" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="stream-attribute-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="stream-element-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="stream-enumerated-type">
		<xs:sequence>
			<xs:element name="value" type="enum-type" default="STRING"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="stream-temporal-type">
		<xs:sequence>
			<xs:element name="pattern" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="stream-transient-type"/>
	
	<xs:simpleType name="enum-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="STRING" />
			<xs:enumeration value="ORDINAL" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== AdsonRoberto/InterfacesCustomizadasJB/JBEmptyProject/app/src/main/assets/config/mapping/stream/jb-stream-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<jb-stream-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schema/jb-stream-mapping.xsd">
	<entity class="org.jb.model.Produto">
		<stream-entity collectionName="produtoes" name="produto" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<stream-attribute>
				<name>id</name>
			</stream-attribute>
		</attribute>
		<attribute name="descricao" type="java.lang.String"
			enclosing-type="java.lang.String">
			<stream-attribute>
				<name>descricao</name>
			</stream-attribute>
		</attribute>
		<attribute name="valor" type="java.lang.Double"
			enclosing-type="java.lang.Double">
			<stream-attribute>
				<name>valor</name>
			</stream-attribute>
		</attribute>
		<attribute name="catalogos" type="java.util.List"
			enclosing-type="org.jb.model.Catalogo">
			<stream-transient></stream-transient>
		</attribute>
	</entity>
	<entity class="org.jb.model.Catalogo">
		<stream-entity collectionName="catalogoes" name="catalogo" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<stream-attribute>
				<name>id</name>
			</stream-attribute>
		</attribute>
		<attribute name="nome" type="java.lang.String"
			enclosing-type="java.lang.String">
			<stream-attribute>
				<name>nome</name>
			</stream-attribute>
		</attribute>
		<attribute name="descricao" type="java.lang.String"
			enclosing-type="java.lang.String">
			<stream-attribute>
				<name>descricao</name>
			</stream-attribute>
		</attribute>
		<attribute name="produtos" type="java.util.List"
			enclosing-type="org.jb.model.Produto">
			<stream-transient />
		</attribute>
	</entity>
	<entity class="org.jb.model.Cliente">
		<stream-entity collectionName="clientes" name="cliente" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<stream-attribute>
				<name>id</name>
			</stream-attribute>
		</attribute>
		<attribute name="nome" type="java.lang.String"
			enclosing-type="java.lang.String">
			<stream-attribute>
				<name>nome</name>
			</stream-attribute>
		</attribute>
		<attribute name="sexo" type="org.jb.model.Sexo"
			enclosing-type="org.jb.model.Sexo">
			<stream-element>
				<name>sexo</name>
			</stream-element>
		</attribute>
		<attribute name="dataNascimento" type="java.util.Date"
			enclosing-type="java.util.Date">
			<stream-attribute>
				<name>dataDeNascimento</name>
			</stream-attribute>
			<stream-temporal>
				<pattern>yyyy-MM-dd'T'HH:mm:ss</pattern>
			</stream-temporal>
		</attribute>
		<attribute name="pedidos" type="java.util.List"
			enclosing-type="org.jb.model.Pedido">
			<stream-transient></stream-transient>
		</attribute>
	</entity>
	<entity class="org.jb.model.Item">
		<stream-entity collectionName="items" name="item" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<stream-attribute>
				<name>id</name>
			</stream-attribute>
		</attribute>
		<attribute name="pedido" type="org.jb.model.Pedido"
			enclosing-type="org.jb.model.Pedido">
			<stream-element>
				<name>pedido</name>
			</stream-element>
		</attribute>
		<attribute name="produto" type="org.jb.model.Produto"
			enclosing-type="org.jb.model.Produto">
			<stream-element>
				<name>produto</name>
			</stream-element>
		</attribute>
		<attribute name="quantidade" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<stream-attribute>
				<name>quantidade</name>
			</stream-attribute>
		</attribute>
		<attribute name="valor" type="java.lang.Double"
			enclosing-type="java.lang.Double">
			<stream-attribute>
				<name>valor</name>
			</stream-attribute>
		</attribute>
	</entity>
	<entity class="org.jb.model.Pedido">
		<stream-entity collectionName="pedidos" name="pedido" />
		<attribute name="id" type="java.lang.Integer"
			enclosing-type="java.lang.Integer">
			<stream-attribute>
				<name>id</name>
			</stream-attribute>
		</attribute>
		<attribute name="cliente" type="org.jb.model.Cliente"
			enclosing-type="org.jb.model.Cliente">
			<stream-element>
				<name>cliente</name>
			</stream-element>
		</attribute>
		<attribute name="data" type="java.util.Date" enclosing-type="java.util.Date">
			<stream-attribute>
				<name>data</name>
			</stream-attribute>
			<stream-temporal>
				<pattern>yyyy-MM-dd'T'HH:mm:ss</pattern>
			</stream-temporal>
		</attribute>
		<attribute name="situacao" type="org.jb.model.SituacaoPedido"
			enclosing-type="org.jb.model.SituacaoPedido">
			<stream-element>
				<name>situacao</name>
			</stream-element>
		</attribute>
		<attribute name="itens" type="java.util.List"
			enclosing-type="org.jb.model.Item">
			<stream-transient></stream-transient>
		</attribute>
	</entity>
</jb-stream-mapping>
